# -*- coding: utf-8 -*-
"""sleep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AydROqwtwmlJhCjKt3EsdXbgg_qagiCa
"""

# ==========================
# 1️⃣ Import Libraries
# ==========================
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

# ==========================
# 2️⃣ Load Dataset
# ==========================
df = pd.read_csv('/content/Sleep_health_and_lifestyle_dataset.csv')
df = df.fillna('')

# ==========================
# 3️⃣ Data Preprocessing
# ==========================
# Find the correct Blood Pressure column automatically
bp_col = [col for col in df.columns if 'Blood' in col][0]

# Split it into Systolic / Diastolic
df[['Systolic', 'Diastolic']] = df[bp_col].str.split('/', expand=True)
df['Systolic'] = pd.to_numeric(df['Systolic'], errors='coerce')
df['Diastolic'] = pd.to_numeric(df['Diastolic'], errors='coerce')
df.drop(bp_col, axis=1, inplace=True)


# Encode Target
label_encoder = LabelEncoder()
df['Sleep Disorder'] = label_encoder.fit_transform(df['Sleep Disorder'])
print("\nLabel Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))
# Example: {'None': 0, 'Insomnia': 1, 'Sleep Apnea': 2}

# Separate features and target
Y = df['Sleep Disorder']
X = df.drop(['Sleep Disorder', 'Person ID'], axis=1)

# Define categorical columns
categorical_features = ['Gender', 'Occupation', 'BMI Category']

# OneHotEncode categorical features
onehot = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
preprocessor = ColumnTransformer(transformers=[
    ('cat', onehot, categorical_features)
], remainder='passthrough')

# Transform X
X_processed = preprocessor.fit_transform(X)

# Handle class imbalance
sm = SMOTE(random_state=42)
X_resampled, Y_resampled = sm.fit_resample(X_processed, Y)

# ==========================
# 4️⃣ Train-Test Split
# ==========================
X_train, X_test, Y_train, Y_test = train_test_split(
    X_resampled, Y_resampled, test_size=0.2, random_state=42)

# ==========================
# 5️⃣ Train Random Forest
# ==========================
rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_leaf=3,
    class_weight='balanced_subsample',
    random_state=42
)
rf_model.fit(X_train, Y_train)

# ==========================
# 6️⃣ Evaluate Model
# ==========================
train_pred = rf_model.predict(X_train)
test_pred = rf_model.predict(X_test)

print("\nTrain Accuracy:", accuracy_score(Y_train, train_pred))
print("Test Accuracy:", accuracy_score(Y_test, test_pred))
print("\nClassification Report:\n", classification_report(Y_test, test_pred))
print("\nConfusion Matrix:\n", confusion_matrix(Y_test, test_pred))

# ==========================
# 7️⃣ Single Prediction Example
# ==========================
input_data = {
    'Gender': 'Male',
    'Age': 28,
    'Occupation': 'Software Engineer',
    'Sleep Duration': 5.9, # Changed from 'Sleep Duration (hours)'
    'Quality of Sleep': 4, # Changed from 'Quality of Sleep (scale: 1-10)'
    'Physical Activity Level': 30, # Changed from 'Physical Activity Level (minutes/day)'
    'Stress Level': 8, # Changed from 'Stress Level (scale: 1-10)'
    'BMI Category': 'Obese',
    'Systolic': 140,
    'Diastolic': 90,
    'Heart Rate': 85,
    'Daily Steps': 3000
}

# Convert to DataFrame and transform, ensuring column names and order match X
input_df = pd.DataFrame([input_data], columns=X.columns)
input_processed = preprocessor.transform(input_df)

# Predict numeric
prediction_numeric = rf_model.predict(input_processed)[0]

# Map to label
mapping = {0: "No Disorder", 1: "Insomnia", 2: "Sleep Apnea"}
print("\nPredicted Sleep Disorder (numeric):", prediction_numeric)
print("Predicted Sleep Disorder:", mapping.get(prediction_numeric, "Unknown"))

import pickle
with open('sleep_rf_model.pkl', 'wb') as f:
    pickle.dump(rf_model, f)
with open('sleep_preprocessor.pkl', 'wb') as f:
    pickle.dump(preprocessor, f)
with open('label_encoder.pkl.pkl', 'wb') as f:
    pickle.dump(label_encoder, f)